### ISSUE TITLE
Incompatible with Picasso 2.71828

### ISSUE THREAD

**Issue by etanhatch** [JakeWharton/picasso2-okhttp3-downloader#30] opened 2018-04-09 11:43 UTC
With latest version of Picasso (2.71828) this library gives the following error (in downloader.load):

"No such instance method: com.squareup.picasso.Downloader.Response com.jakewharton.picasso.OkHttp3Downloader.load(android.net.Uri, int)"

**Comment by vanniktech** [comment] 2018-04-09 11:44
Dupe of #29

**Closed** 2018-04-09 11:47 UTC
